/**
 * CodeEditor.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RefreshTokensRequestUserId } from './refreshTokensRequestUserId';


export interface RefreshTokensRequest { 
    userId?: RefreshTokensRequestUserId;
    refreshToken?: string;
}

