/**
 * CodeEditor.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserResponseId } from './userResponseId';


export interface UserResponse { 
    id?: UserResponseId;
    userName?: string;
    guid?: string;
}

