<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-CodeEditor.Worker-f110eb71-d1b4-45e9-ae2f-2dc4fd0f6e2e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cronos" Version="0.11.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CodeEditor.Domain\CodeEditor.Domain.csproj" />
    <ProjectReference Include="..\CodeEditor.Infrastructure\CodeEditor.Infrastructure.csproj" />
  </ItemGroup>
</Project>
