services:
  rabbitmmq:
    image: rabbitmq:management
    container_name: rabbitmq_container
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_volume:/var/lib/rabbitmq
      - ./Rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./Rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  rabbitmq_volume: