// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetApiAuthStatusData, GetApiAuthStatusResponses, GetApiGitFeedEntryGetEntriesByGitFeedIdByGitFeedIdData, GetApiGitFeedEntryGetEntriesByGitFeedIdByGitFeedIdErrors, GetApiGitFeedEntryGetEntriesByGitFeedIdByGitFeedIdResponses, GetApiGitRepoByGitRepoIdData, GetApiGitRepoByGitRepoIdErrors, GetApiGitRepoByGitRepoIdResponses, GetApiGitRepoGetAllGitRepoSummaryData, GetApiGitRepoGetAllGitRepoSummaryErrors, GetApiGitRepoGetAllGitRepoSummaryResponses, GetApiGitRepoGetUserGitReposByUserGuidData, GetApiGitRepoGetUserGitReposByUserGuidErrors, GetApiGitRepoGetUserGitReposByUserGuidResponses, GetApiUserByIdData, GetApiUserByIdResponses, PostApiAuthCreateAccountData, PostApiAuthCreateAccountResponses, PostApiAuthLoginData, PostApiAuthLoginResponses, PostApiAuthRefreshData, PostApiAuthRefreshResponses, PostApiGitRepoData, PostApiGitRepoErrors, PostApiGitRepoResponses, PostApiGitRepoSetUserAllGitRepoByUserGuidData, PostApiGitRepoSetUserAllGitRepoByUserGuidErrors, PostApiGitRepoSetUserAllGitRepoByUserGuidResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class GitFeedEntry {
    public static getApiGitFeedEntryGetEntriesByGitFeedIdByGitFeedId<ThrowOnError extends boolean = false>(options: Options<GetApiGitFeedEntryGetEntriesByGitFeedIdByGitFeedIdData, ThrowOnError>) {
        return (options.client ?? client).get<GetApiGitFeedEntryGetEntriesByGitFeedIdByGitFeedIdResponses, GetApiGitFeedEntryGetEntriesByGitFeedIdByGitFeedIdErrors, ThrowOnError>({ url: '/api/GitFeedEntry/getEntriesByGitFeedId/{gitFeedId}', ...options });
    }
}

export class Auth {
    public static postApiAuthLogin<ThrowOnError extends boolean = false>(options: Options<PostApiAuthLoginData, ThrowOnError>) {
        return (options.client ?? client).post<PostApiAuthLoginResponses, unknown, ThrowOnError>({
            url: '/api/Auth/login',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static postApiAuthCreateAccount<ThrowOnError extends boolean = false>(options: Options<PostApiAuthCreateAccountData, ThrowOnError>) {
        return (options.client ?? client).post<PostApiAuthCreateAccountResponses, unknown, ThrowOnError>({
            url: '/api/Auth/createAccount',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static postApiAuthRefresh<ThrowOnError extends boolean = false>(options?: Options<PostApiAuthRefreshData, ThrowOnError>) {
        return (options?.client ?? client).post<PostApiAuthRefreshResponses, unknown, ThrowOnError>({ url: '/api/Auth/refresh', ...options });
    }
    
    public static getApiAuthStatus<ThrowOnError extends boolean = false>(options?: Options<GetApiAuthStatusData, ThrowOnError>) {
        return (options?.client ?? client).get<GetApiAuthStatusResponses, unknown, ThrowOnError>({ url: '/api/Auth/status', ...options });
    }
}

export class GitRepo {
    /**
     * Get the GitRepo thank to the given id
     */
    public static getApiGitRepoByGitRepoId<ThrowOnError extends boolean = false>(options: Options<GetApiGitRepoByGitRepoIdData, ThrowOnError>) {
        return (options.client ?? client).get<GetApiGitRepoByGitRepoIdResponses, GetApiGitRepoByGitRepoIdErrors, ThrowOnError>({ url: '/api/GitRepo/{gitRepoId}', ...options });
    }
    
    /**
     * Add a GitRepo
     */
    public static postApiGitRepo<ThrowOnError extends boolean = false>(options: Options<PostApiGitRepoData, ThrowOnError>) {
        return (options.client ?? client).post<PostApiGitRepoResponses, PostApiGitRepoErrors, ThrowOnError>({
            url: '/api/GitRepo',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Get all GitRepoSummary stored in database
     */
    public static getApiGitRepoGetAllGitRepoSummary<ThrowOnError extends boolean = false>(options?: Options<GetApiGitRepoGetAllGitRepoSummaryData, ThrowOnError>) {
        return (options?.client ?? client).get<GetApiGitRepoGetAllGitRepoSummaryResponses, GetApiGitRepoGetAllGitRepoSummaryErrors, ThrowOnError>({ url: '/api/GitRepo/getAllGitRepoSummary', ...options });
    }
    
    /**
     * Set all GitRepo linked to the given userId
     */
    public static postApiGitRepoSetUserAllGitRepoByUserGuid<ThrowOnError extends boolean = false>(options: Options<PostApiGitRepoSetUserAllGitRepoByUserGuidData, ThrowOnError>) {
        return (options.client ?? client).post<PostApiGitRepoSetUserAllGitRepoByUserGuidResponses, PostApiGitRepoSetUserAllGitRepoByUserGuidErrors, ThrowOnError>({ url: '/api/GitRepo/setUserAllGitRepo/{userGuid}', ...options });
    }
    
    /**
     * Used to retrieve all GitRepos entities link to the specified user
     */
    public static getApiGitRepoGetUserGitReposByUserGuid<ThrowOnError extends boolean = false>(options: Options<GetApiGitRepoGetUserGitReposByUserGuidData, ThrowOnError>) {
        return (options.client ?? client).get<GetApiGitRepoGetUserGitReposByUserGuidResponses, GetApiGitRepoGetUserGitReposByUserGuidErrors, ThrowOnError>({ url: '/api/GitRepo/getUserGitRepos/{userGuid}', ...options });
    }
}

export class User {
    public static getApiUserById<ThrowOnError extends boolean = false>(options: Options<GetApiUserByIdData, ThrowOnError>) {
        return (options.client ?? client).get<GetApiUserByIdResponses, unknown, ThrowOnError>({ url: '/api/User/{id}', ...options });
    }
}
