// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetApiAuthStatusData, GetApiAuthStatusResponses, GetApiUserByIdData, GetApiUserByIdResponses, PostApiAuthCreateAccountData, PostApiAuthCreateAccountResponses, PostApiAuthLoginData, PostApiAuthLoginResponses, PostApiAuthRefreshData, PostApiAuthRefreshResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class Auth {
    public static postApiAuthLogin<ThrowOnError extends boolean = false>(options: Options<PostApiAuthLoginData, ThrowOnError>) {
        return (options.client ?? client).post<PostApiAuthLoginResponses, unknown, ThrowOnError>({
            url: '/api/Auth/login',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static postApiAuthCreateAccount<ThrowOnError extends boolean = false>(options: Options<PostApiAuthCreateAccountData, ThrowOnError>) {
        return (options.client ?? client).post<PostApiAuthCreateAccountResponses, unknown, ThrowOnError>({
            url: '/api/Auth/createAccount',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static postApiAuthRefresh<ThrowOnError extends boolean = false>(options?: Options<PostApiAuthRefreshData, ThrowOnError>) {
        return (options?.client ?? client).post<PostApiAuthRefreshResponses, unknown, ThrowOnError>({ url: '/api/Auth/refresh', ...options });
    }
    
    public static getApiAuthStatus<ThrowOnError extends boolean = false>(options?: Options<GetApiAuthStatusData, ThrowOnError>) {
        return (options?.client ?? client).get<GetApiAuthStatusResponses, unknown, ThrowOnError>({ url: '/api/Auth/status', ...options });
    }
}

export class User {
    public static getApiUserById<ThrowOnError extends boolean = false>(options: Options<GetApiUserByIdData, ThrowOnError>) {
        return (options.client ?? client).get<GetApiUserByIdResponses, unknown, ThrowOnError>({ url: '/api/User/{id}', ...options });
    }
}
