// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:7127/' | (string & {});
};

export type CreateAccountRequest = {
    userName?: string;
    password?: string;
    confirmPassword?: string;
};

export type LoginRequest = {
    userName?: string;
    password?: string;
};

export type UserResponse = {
    id?: unknown;
    userName?: string;
    guid?: string;
};

export type PostApiAuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/Auth/login';
};

export type PostApiAuthLoginResponses = {
    /**
     * OK
     */
    200: UserResponse;
};

export type PostApiAuthLoginResponse = PostApiAuthLoginResponses[keyof PostApiAuthLoginResponses];

export type PostApiAuthCreateAccountData = {
    body: CreateAccountRequest;
    path?: never;
    query?: never;
    url: '/api/Auth/createAccount';
};

export type PostApiAuthCreateAccountResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAuthRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Auth/refresh';
};

export type PostApiAuthRefreshResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type PostApiAuthRefreshResponse = PostApiAuthRefreshResponses[keyof PostApiAuthRefreshResponses];

export type GetApiAuthStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Auth/status';
};

export type GetApiAuthStatusResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiUserByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/User/{id}';
};

export type GetApiUserByIdResponses = {
    /**
     * OK
     */
    200: UserResponse;
};

export type GetApiUserByIdResponse = GetApiUserByIdResponses[keyof GetApiUserByIdResponses];
