// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5242/' | (string & {});
};

export type AddGitRepoRequest = {
    url?: string;
    ownerName?: string;
    name?: string;
};

export type CreateAccountRequest = {
    userName?: string;
    password?: string;
    confirmPassword?: string;
};

export type GitFeed = {
    title?: string;
    lastUpdateDate?: string;
    gitFeedEntries?: Array<GitFeedEntry>;
    gitRepoId?: number;
    id?: number;
    rowVersion?: number;
    creationDate?: string;
    lastModificationDate?: string;
};

export type GitFeedEntry = {
    gitFeedId?: number;
    idTag?: string;
    lastUpdateDate?: string;
    link?: string;
    title?: string;
    content?: string;
    authorName?: string;
    id?: number;
    rowVersion?: number;
    creationDate?: string;
    lastModificationDate?: string;
};

export type GitFeedEntryResponse = {
    gitFeedId?: number;
    idTag?: string;
    lastUpdateDate?: string;
    link?: string;
    title?: string;
    content?: string;
    authorName?: string;
};

export type GitRepoResponse = {
    id?: number;
    idGitFeed?: number;
    ownerName?: string;
    name?: string;
    url?: string;
    lastUpdateDate?: string;
    gitFeed?: GitFeed;
};

export type GitRepoTitleResponse = {
    id?: number;
    title?: string;
};

export type IActionResult = {
    [key: string]: unknown;
};

export type LoginRequest = {
    userName?: string;
    password?: string;
};

export type UserResponse = {
    id?: number;
    userName?: string;
    guid?: string;
};

export type ValidationProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: unknown;
    detail?: string | null;
    instance?: string | null;
    errors?: {
        [key: string]: Array<string>;
    };
};

export type GetApiGitFeedEntryGetEntriesByGitFeedIdByGitFeedIdData = {
    body?: never;
    path: {
        gitFeedId: number;
    };
    query?: never;
    url: '/api/GitFeedEntry/getEntriesByGitFeedId/{gitFeedId}';
};

export type GetApiGitFeedEntryGetEntriesByGitFeedIdByGitFeedIdErrors = {
    /**
     * Bad Request
     */
    400: ValidationProblemDetails;
};

export type GetApiGitFeedEntryGetEntriesByGitFeedIdByGitFeedIdError = GetApiGitFeedEntryGetEntriesByGitFeedIdByGitFeedIdErrors[keyof GetApiGitFeedEntryGetEntriesByGitFeedIdByGitFeedIdErrors];

export type GetApiGitFeedEntryGetEntriesByGitFeedIdByGitFeedIdResponses = {
    /**
     * OK
     */
    200: Array<GitFeedEntryResponse>;
};

export type GetApiGitFeedEntryGetEntriesByGitFeedIdByGitFeedIdResponse = GetApiGitFeedEntryGetEntriesByGitFeedIdByGitFeedIdResponses[keyof GetApiGitFeedEntryGetEntriesByGitFeedIdByGitFeedIdResponses];

export type PostApiAuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/Auth/login';
};

export type PostApiAuthLoginResponses = {
    /**
     * OK
     */
    200: UserResponse;
};

export type PostApiAuthLoginResponse = PostApiAuthLoginResponses[keyof PostApiAuthLoginResponses];

export type PostApiAuthCreateAccountData = {
    body: CreateAccountRequest;
    path?: never;
    query?: never;
    url: '/api/Auth/createAccount';
};

export type PostApiAuthCreateAccountResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiAuthRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Auth/refresh';
};

export type PostApiAuthRefreshResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type PostApiAuthRefreshResponse = PostApiAuthRefreshResponses[keyof PostApiAuthRefreshResponses];

export type GetApiAuthStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Auth/status';
};

export type GetApiAuthStatusResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiGitRepoByGitRepoIdData = {
    body?: never;
    path: {
        gitRepoId: number;
    };
    query?: never;
    url: '/api/GitRepo/{gitRepoId}';
};

export type GetApiGitRepoByGitRepoIdErrors = {
    /**
     * Bad Request
     */
    400: ValidationProblemDetails;
};

export type GetApiGitRepoByGitRepoIdError = GetApiGitRepoByGitRepoIdErrors[keyof GetApiGitRepoByGitRepoIdErrors];

export type GetApiGitRepoByGitRepoIdResponses = {
    /**
     * OK
     */
    200: GitRepoResponse;
    /**
     * No Content
     */
    204: GitRepoResponse;
};

export type GetApiGitRepoByGitRepoIdResponse = GetApiGitRepoByGitRepoIdResponses[keyof GetApiGitRepoByGitRepoIdResponses];

export type PostApiGitRepoData = {
    body: AddGitRepoRequest;
    path?: never;
    query?: never;
    url: '/api/GitRepo';
};

export type PostApiGitRepoErrors = {
    /**
     * Bad Request
     */
    400: ValidationProblemDetails;
};

export type PostApiGitRepoError = PostApiGitRepoErrors[keyof PostApiGitRepoErrors];

export type PostApiGitRepoResponses = {
    /**
     * Created
     */
    201: GitRepoResponse;
};

export type PostApiGitRepoResponse = PostApiGitRepoResponses[keyof PostApiGitRepoResponses];

export type GetApiGitRepoGetAllGitRepoSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/GitRepo/getAllGitRepoSummary';
};

export type GetApiGitRepoGetAllGitRepoSummaryErrors = {
    /**
     * Bad Request
     */
    400: ValidationProblemDetails;
};

export type GetApiGitRepoGetAllGitRepoSummaryError = GetApiGitRepoGetAllGitRepoSummaryErrors[keyof GetApiGitRepoGetAllGitRepoSummaryErrors];

export type GetApiGitRepoGetAllGitRepoSummaryResponses = {
    /**
     * OK
     */
    200: Array<GitRepoTitleResponse>;
    /**
     * No Content
     */
    204: IActionResult;
};

export type GetApiGitRepoGetAllGitRepoSummaryResponse = GetApiGitRepoGetAllGitRepoSummaryResponses[keyof GetApiGitRepoGetAllGitRepoSummaryResponses];

export type PostApiGitRepoSetUserAllGitRepoByUserGuidData = {
    body?: never;
    path: {
        userGuid: string;
    };
    query?: never;
    url: '/api/GitRepo/setUserAllGitRepo/{userGuid}';
};

export type PostApiGitRepoSetUserAllGitRepoByUserGuidErrors = {
    /**
     * Bad Request
     */
    400: ValidationProblemDetails;
};

export type PostApiGitRepoSetUserAllGitRepoByUserGuidError = PostApiGitRepoSetUserAllGitRepoByUserGuidErrors[keyof PostApiGitRepoSetUserAllGitRepoByUserGuidErrors];

export type PostApiGitRepoSetUserAllGitRepoByUserGuidResponses = {
    /**
     * OK
     */
    200: Array<GitRepoResponse>;
    /**
     * No Content
     */
    204: IActionResult;
};

export type PostApiGitRepoSetUserAllGitRepoByUserGuidResponse = PostApiGitRepoSetUserAllGitRepoByUserGuidResponses[keyof PostApiGitRepoSetUserAllGitRepoByUserGuidResponses];

export type GetApiGitRepoGetUserGitReposByUserGuidData = {
    body?: never;
    path: {
        userGuid: string;
    };
    query?: never;
    url: '/api/GitRepo/getUserGitRepos/{userGuid}';
};

export type GetApiGitRepoGetUserGitReposByUserGuidErrors = {
    /**
     * Bad Request
     */
    400: ValidationProblemDetails;
};

export type GetApiGitRepoGetUserGitReposByUserGuidError = GetApiGitRepoGetUserGitReposByUserGuidErrors[keyof GetApiGitRepoGetUserGitReposByUserGuidErrors];

export type GetApiGitRepoGetUserGitReposByUserGuidResponses = {
    /**
     * OK
     */
    200: Array<GitRepoResponse>;
};

export type GetApiGitRepoGetUserGitReposByUserGuidResponse = GetApiGitRepoGetUserGitReposByUserGuidResponses[keyof GetApiGitRepoGetUserGitReposByUserGuidResponses];

export type GetApiUserByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/User/{id}';
};

export type GetApiUserByIdResponses = {
    /**
     * OK
     */
    200: UserResponse;
};

export type GetApiUserByIdResponse = GetApiUserByIdResponses[keyof GetApiUserByIdResponses];
