// <auto-generated />
using System;
using CodeEditor.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeEditor.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260310192628_FlattenEntitiesLinks")]
    partial class FlattenEntitiesLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeEditor.Domain.Entities.GitFeed", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("GitRepoId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("git_feeds", (string)null);
                });

            modelBuilder.Entity("CodeEditor.Domain.Entities.GitFeedEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("author_name");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<long>("GitFeedId")
                        .HasColumnType("bigint")
                        .HasColumnName("git_feed_id");

                    b.Property<string>("IdTag")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("id_tag");

                    b.Property<DateTimeOffset>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("link");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("GitFeedId");

                    b.ToTable("git_feed_entries", (string)null);
                });

            modelBuilder.Entity("CodeEditor.Domain.Entities.GitRepo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdGitFeed")
                        .HasColumnType("bigint")
                        .HasColumnName("id_git_feed");

                    b.Property<DateTimeOffset>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("owner_name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("IdGitFeed")
                        .IsUnique();

                    b.ToTable("git_repos", (string)null);
                });

            modelBuilder.Entity("CodeEditor.Domain.Entities.Token", b =>
                {
                    b.Property<string>("RefreshToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("refresh_token");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("RefreshToken", "UserId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("tokens", (string)null);
                });

            modelBuilder.Entity("CodeEditor.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("Guid")
                        .HasMaxLength(500)
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CodeEditor.Domain.Entities.UserGitRepo", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("GitRepoId")
                        .HasColumnType("bigint")
                        .HasColumnName("git_repo_id");

                    b.HasKey("UserId", "GitRepoId");

                    b.HasIndex("GitRepoId");

                    b.ToTable("user_git_repo", (string)null);
                });

            modelBuilder.Entity("CodeEditor.Domain.Entities.GitFeedEntry", b =>
                {
                    b.HasOne("CodeEditor.Domain.Entities.GitFeed", null)
                        .WithMany("GitFeedEntries")
                        .HasForeignKey("GitFeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CodeEditor.Domain.Entities.GitRepo", b =>
                {
                    b.HasOne("CodeEditor.Domain.Entities.GitFeed", "GitFeed")
                        .WithOne()
                        .HasForeignKey("CodeEditor.Domain.Entities.GitRepo", "IdGitFeed")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GitFeed");
                });

            modelBuilder.Entity("CodeEditor.Domain.Entities.Token", b =>
                {
                    b.HasOne("CodeEditor.Domain.Entities.User", "User")
                        .WithOne("Token")
                        .HasForeignKey("CodeEditor.Domain.Entities.Token", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodeEditor.Domain.Entities.UserGitRepo", b =>
                {
                    b.HasOne("CodeEditor.Domain.Entities.GitRepo", "GitRepo")
                        .WithMany()
                        .HasForeignKey("GitRepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeEditor.Domain.Entities.User", "User")
                        .WithMany("UserGitRepos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GitRepo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodeEditor.Domain.Entities.GitFeed", b =>
                {
                    b.Navigation("GitFeedEntries");
                });

            modelBuilder.Entity("CodeEditor.Domain.Entities.User", b =>
                {
                    b.Navigation("Token")
                        .IsRequired();

                    b.Navigation("UserGitRepos");
                });
#pragma warning restore 612, 618
        }
    }
}
